name: andipublisher
version: 3.0.3+3
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  syncfusion_flutter_pdfviewer: ^23.2.4
  intl: ^0.18.1
  http: ^1.1.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter: 
    sdk: flutter
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1
  get_storage: ^2.1.1
  ionicons: ^0.2.2
  url_launcher: ^6.1.11
  cached_network_image: ^3.3.0
  lottie: ^2.4.0
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_inappwebview: ^5.7.2+3
  badges: ^3.1.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.1
  flutter_windowmanager: ^0.2.0
  animated_button: ^0.2.0
  dio: ^5.3.3
  flutter_spinkit: ^5.2.0
  flutter_downloader: ^1.11.4
  staggered_grid_view_flutter: ^0.0.4
  flutter_countdown_timer: ^4.1.0
  timeago: ^3.6.0
  material_color_utilities: ^0.5.0
  flutter_svg: ^1.1.6  
  shimmer: ^3.0.0

dev_dependencies: 
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/

