name: andipublisher
version: 2.0.2+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  syncfusion_flutter_pdfviewer: ^20.4.54
  intl: ^0.18.1
  http: ^0.13.6
  google_fonts: ^4.0.4
  get: 4.6.5
  flutter: 
    sdk: flutter
  connectivity_plus: ^4.0.1
  package_info_plus: ^4.0.2
  get_storage: ^2.1.1
  ionicons: ^0.2.2
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3
  lottie: ^2.4.0
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_inappwebview: ^5.7.2+3
  badges: ^3.1.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.1
  flutter_windowmanager: ^0.2.0
  animated_button: ^0.2.0
  pspdfkit_flutter: ^3.7.0
  dio: ^5.3.3
  flutter_spinkit: ^5.2.0
  flutter_downloader: ^1.11.4


dev_dependencies: 
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/

